options:
  prev_tag: versio-prev

projects:
- name: fix-compaudit
  id: 1
  tag_prefix: ''
  labels: cargo
  version:
    file: Cargo.toml
    toml: package.version
  hooks:
    post_write: cargo fetch

sizes:
  major: ['!']
  minor: [feat]
  patch: [deps, fix, ci, docs, style, refactor, perf, test, chore, build]
  none: []
  fail: ['*']
