[package]
name = "fix-compaudit"
version = "0.3.1"
authors = ["Billie Thompson <billie@billiecodes.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
users = "0.10"
clap = "~2.33"

[dev-dependencies]
tempfile = "3"